test = {   'name': 'q2a',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> prob_at_most(3, 0.4, 1) >= 0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> prob_at_most(5, 0.6, 3) <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> prob_at_most(2, 3, 4) == 0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(prob_at_most(10, 0.7, 4), 0.0473, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_at_most(10, 0.7, 4), 0.0473, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_at_most(5, 1, 1), 0, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_at_most(8, 0.7, 3), 0.05797, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
