test = {   'name': 'q3c',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> np.isclose(prob_sample_counts(31, 8, 1), 0, atol = 1e-5)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= prob_sample_counts(2, 5, 13) <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= prob_sample_counts(5, 1, 14) <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= prob_sample_counts(10, 8, 2) <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= prob_sample_counts(6, 12, 2) <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> prob_sample_counts(6, 12, 8) == 0\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> prob_sample_counts(21, 0, 3) == 0\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> prob_sample_counts(6, 6, 2) == 0\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_sample_counts(6, 12, 2), 0.01095, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_sample_counts(13, 7, 0), 0.03169, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(prob_sample_counts(13, 5, 2), 0.00562, atol = 1e-4)\nTrue', 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
